/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_SilirdCo_ConnectCPPLib_jniDinlib_DynlibJNI */

#ifndef _Included_ru_SilirdCo_ConnectCPPLib_jniDinlib_DynlibJNI
#define _Included_ru_SilirdCo_ConnectCPPLib_jniDinlib_DynlibJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_SilirdCo_ConnectCPPLib_jniDinlib_DynlibJNI
 * Method:    getSqrt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_ru_SilirdCo_ConnectCPPLib_jniDinlib_DynlibJNI_getSqrt
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
