/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_silirdco_connectcpplib_jni_HelloWorldJNI */

#ifndef _Included_ru_silirdco_connectcpplib_jni_HelloWorldJNI
#define _Included_ru_silirdco_connectcpplib_jni_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_silirdco_connectcpplib_jni_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_silirdco_connectcpplib_jni_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
